openapi: 3.0.0
info:
  title: VideoPlayer API
  description: think well
  version: 0.1.0
servers:
  - url: https://localhost:3000/api
    description: local
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: ..
      responses:
        '200':    # status code
          description: ..
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string