openapi: 3.0.0
info:
  title: VideoPlayer API
  description: _
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
    description: local
  - url: https://videoplayerlatest.herokuapp.com/api
    description: remote

# components:
#   securitySchemes:
#     cookieAuth:
#       type: apiKey
#       in: cookie
#       name: token_access 

paths:
  /users/create:
    post:
      tags:
        - users
      summary: User create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '202':
          description: success
          # headers: 
          #   Set-Cookie:
          #     schema: 
          #       type: string
          #       example: JSESSIONID=abcde12345; Path=/; HttpOnly
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: "success"
                  token_refresh:
                    type: string
                    example: eyJhb
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    example: '...'
  
  /users/auth:
    post:
      tags:
        - users
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: "success"
                  token_refresh:
                    type: string
                    example: eyJhb
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    example: '...'
  
  /users/logout:
    post:
      tags:
        - users
      security:
        - cookieAuth: []
      summary: User logout
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: "logout"
        '401':
          description: error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "invalid access"
  
  /users/refresh:
    post:
      tags:
        - users
      security:
        - cookieAuth: []
      summary: Token refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenRefresh:
                  type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    example: "success"
                  token_refresh:
                    type: string
                    example: eyJhb
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "invalid access"
                    
  /video/getInfo:
    post:
      tags:
       - video
      summary: get information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link:
                  type: string
                  example: https://www.youtube.com/watch?v=qANA6POtuFo
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  video_identifier:
                    example: "qANA6POtuFo"
                  title:
                    type: string
                    example: "How to Download YouTube Subtitles as Text"
                  description:
                    type: string
                    example: "In this video ..."
                  thumbnails:
                    type: string
                    example: "https://i.ytimg.com/vi/qANA6POtuFo/mqdefault.jpg"
                  
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "..."
                    
  /video/subtitlesToHash:
    post:
      tags:
       - video
      summary: get words and transcription from subtitles
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subtitles:
                  type: object
                  properties:
                    text:
                      type: array
                      items:
                        type: object
                        properties:
                          start:
                            type: string
                            example: "0"
                          dur:
                            type: string
                            example: "9.269"
                          $t:
                            type: string
                            example: "Hello, and thank you for, joining me for this tutorial."
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  words:
                    type: object
                    properties: 
                      word:
                        type: string
                      word2:
                        type: boolean
                        example: false
                      word3:
                        type: string
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "..."
                    
  /video/saveInfo:
    post:
      tags:
       - video
      summary: save information about video
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                video_identifier:
                  type: string
                  example: "qANA6POtuFo"
                title:
                  type: string
                  example: "test"
                description:
                  type: string
                  example: "test"
                thumbnails:
                  type: string
                  example: "https://i.ytimg.com/vi/-8b_xY8tpQQ/mqdefault.jpg"  
                  
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 4
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "..."
                    
  /video/addToFavorites:
    post:
      tags:
       - video
      security:
        - cookieAuth: [] 
      summary: add video to favorites
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                video_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "..."
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "Access not allowed"
                    
  /video/removeFromFavorites:
    post:
      tags:
       - video
      security:
        - cookieAuth: [] 
      summary: remove video from favorites
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                video_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "..."
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    example: "Access not allowed"
                    
  /admin/getWords:
    post:
      tags:
      - admin
      security:
        - cookieAuth: []
      summary: get words from dictionary
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                counter:
                  type: integer
                  example: 1
                page:
                  type: integer
                  example: 1
                withoutTranslation:
                  type: boolean
                protect:
                  type: boolean
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      total:
                        type: integer
                      last_page:
                        type: integer
                      per_page:
                        type: integer
                      current_page:
                        type: integer
                      from:
                        type: integer
                      to:
                        type: integer
                      counterMin:
                        type: integer
                      counterMax:
                        type: integer
                      data: 
                        type: array
                        items:
                          type: object
                          properties:
                            id: 
                              type: integer
                            en:
                              type: string
                            ru:
                              type: string
                            counter:
                              type: integer
                            protect:
                              type: boolean
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors: 
                    type: string
                    example: Access not allowed
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    
  /admin/getSubtitles:
    post:
      tags:
      - admin
      security:
        - cookieAuth: []
      summary: get subtitles from video
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link:
                  type: string
                  example: https://www.youtube.com/watch?v=Ncw-XN7MIws
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  subtitles:
                    type: object
                    properties:
                      text:
                       type: array
                       items: 
                        type: object
                        properties:
                          start: 
                            type: string
                            example: "0"
                          dur:
                            type: string
                            example: "9.269"
                          $t:
                            type: string
                            example: "hello yeah say something back to me\nhello ah okay now in this video"
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors: 
                    type: string
                    example: Access not allowed
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object                    
                    
  /admin/changeWord:
    post:
      tags:
      - admin
      security:
        - cookieAuth: []
      summary: change word in dictionary
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer  
                  example: 123
                counter:
                  type: integer  
                  example: 3
                en: 
                  type: string
                  example: "hello"
                ru: 
                  type: string
                  example: "привет"
                protect:
                  type: boolean
                  example: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: array
                    items:
                     type: integer
                     example: 1
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors: 
                    type: string
                    example: Access not allowed
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object                                      
                    
  /admin/deleteWords:
    post:
      tags:
      - admin
      security:
        - cookieAuth: []
      summary: delete words from dictionary
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                counter:
                  type: integer  
                  example: 3
                ids: 
                  type: array
                  items:
                    type: integer
                  example: [1, 2, 3]
                withoutTranslation: 
                  type: boolean
                  example: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: array
                    items:
                     type: integer
                     example: [1, 2, 3]
        '401':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors: 
                    type: string
                    example: Access not allowed
        '400':
          description: errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
